### ISSUE TITLE
how to run this app on windows?

### ISSUE THREAD

**Issue by shithead548** [Excelian/Angular-Material-ECMA6-Dashboard#12]
I can successfully run this app on ubuntu, however how do I execute the start file to run this app on windows?

**Comment by TusharaFernando** [comment]
Are you able to provide the output from the npm start command

**Comment by TusharaFernando** [comment]
Closed due to lack of information.  I run this on Windows regularly.

**Comment by shithead548** [comment]
![qq 20150726143756](https://cloud.githubusercontent.com/assets/5152365/8892835/eed63524-33a3-11e5-9e41-0248f73024a0.png)
![qq 20150726143938](https://cloud.githubusercontent.com/assets/5152365/8892842/2babfbc8-33a4-11e5-9adb-72f5279b2770.png)
