### ISSUE TITLE
Screenshot needed on github

### ISSUE THREAD

**Issue by TusharaFernando** [Excelian/Angular-Material-ECMA6-Dashboard#7]
![usersettings](https://cloud.githubusercontent.com/assets/6848978/7554734/d4c52884-f72b-11e4-87be-b47090fcfd4f.PNG)

**Comment by hughest** [comment]
2nd screenshot:
![image](https://cloud.githubusercontent.com/assets/7428561/8108646/97eae12e-1049-11e5-8ef5-e8d4a3dd1cd7.png)
